import {TGameSearchResult} from "./types";

export const MOCK_GAMES: TGameSearchResult[] = [
    {
        id: 1,
        title: "The Witcher 3: Wild Hunt",
        description: "Ролевая игра в открытом мире по мотивам книг Анджея Сапковского.",
        image: "/images/witcher3.png",
        year: "2015",
        developer: "CD Projekt Red",
    },
    {
        id: 2,
        title: "Cyberpunk 2077",
        description: "Футуристическая RPG с открытым миром в сеттинге Найт-Сити.",
        image: "/images/cyberpunk2077.png",
        year: "2020",
        developer: "CD Projekt Red",
    },
    {
        id: 3,
        title: "Red Dead Redemption 2",
        description: "Приключенческий вестерн с открытым миром и кинематографическим сюжетом.",
        image: "/images/rdr2.png",
        year: "2018",
        developer: "Rockstar Games",
    },
    {
        id: 4,
        title: "Dark Souls III",
        description: "Хардкорная action RPG с уникальным стилем боя и мрачной атмосферой.",
        image: "/images/darksouls3.png",
        year: "2016",
        developer: "FromSoftware",
    },
    {
        id: 5,
        title: "Elden Ring",
        description: "Фэнтезийная action RPG от создателей Dark Souls и Джорджа Мартина.",
        image: "/images/eldenring.png",
        year: "2022",
        developer: "FromSoftware",
    },
    {
        id: 6,
        title: "Half-Life 2",
        description: "Легендарный шутер от первого лица, изменивший жанр навсегда.",
        image: "/images/halflife2.png",
        year: "2004",
        developer: "Valve",
    },
    {
        id: 7,
        title: "Portal 2",
        description: "Головоломка с порталами и фирменным юмором от Valve.",
        image: "/images/portal2.png",
        year: "2011",
        developer: "Valve",
    },
    {
        id: 8,
        title: "The Legend of Zelda: Breath of the Wild",
        description: "Эпическая игра в открытом мире с акцентом на исследование и свободу действий.",
        image: "/images/zelda_botw.png",
        year: "2017",
        developer: "Nintendo",
    },
    {
        id: 9,
        title: "God of War (2018)",
        description: "Переосмысленный экшен с мифологией скандинавов и драматичным сюжетом.",
        image: "/images/godofwar.png",
        year: "2018",
        developer: "Santa Monica Studio",
    },
    {
        id: 10,
        title: "Minecraft",
        description: "Одна из самых популярных игр в истории, где можно строить и выживать.",
        image: "/images/minecraft.png",
        year: "2011",
        developer: "Mojang Studios",
    },
];
